Lab2/Models/Calc.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab2.Models
{
    public class Calc
    {
        public double first_value { get; set; }
        public double second_value { get; set; }
        public string operation { get; set; }
     
        public double toCalc()
        {
            double result;

            switch (operation)
            {
                case "+":
                    result = first_value + second_value;
                    break;
                case "-":
                    result = first_value - second_value;
                    break;
                case "*":
                    result = first_value * second_value;
                    break;
                case "/":
                    if (second_value == 0)
                    {
                        result = -1;
                        break;
                    }
                    result = first_value / second_value;
                    break;
                default:
                    result = 0;
                    break;
            }
            return result;
        }
    }
}

Lab2/Models/ErrorViewModel.cs
using System;

namespace Lab2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab2/Controllers/CalcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab2.Models;

namespace Lab2.Controllers
{
    public class CalcController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ManualParsingInSingleAction()
        {
            return View();
        }

        public IActionResult ManualParsingInSeparateActions()
        {
            return View();
        }

        public IActionResult ModelBindingParametrs()
        {
            return View();
        }

        public IActionResult ModelBindingSeparateModel()
        {
            return View();
        }

        public IActionResult Count1()
        {
            if (Request.Method.Equals("POST", StringComparison.OrdinalIgnoreCase))
            {
                int value1 = Convert.ToInt32(this.Request.Form["input1"]);
                int value2 = Convert.ToInt32(this.Request.Form["input2"]);
                string operation = this.Request.Form["operation"];

                double result;

                switch (operation)
                {
                    case "+":
                        result = value1 + value2;
                        break;
                    case "-":
                        result = value1 - value2;
                        break;
                    case "*":
                        result = value1 * value2;
                        break;
                    case "/":
                        if (value2 == 0)
                            return View("ZeroErrorCalc");
                        result = value1 / value2;
                        break;
                    default:
                        result = 0;
                        break;
                }

                ViewBag.input1 = value1;
                ViewBag.input2 = value2;
                ViewBag.operation = operation;
                ViewBag.result = result;

            }

            return View("Result");
        }

        [HttpPost, ActionName("Count2")]
        public IActionResult Count2Post()
        {
            if (Request.Method.Equals("POST", StringComparison.OrdinalIgnoreCase))
            {
                int value1 = Convert.ToInt32(this.Request.Form["input1"]);
                int value2 = Convert.ToInt32(this.Request.Form["input2"]);
                string operation = this.Request.Form["operation"];

                double result;

                switch (operation)
                {
                    case "+":
                        result = value1 + value2;
                        break;
                    case "-":
                        result = value1 - value2;
                        break;
                    case "*":
                        result = value1 * value2;
                        break;
                    case "/":
                        if (value2 == 0)
                            return View("ZeroErrorCalc");
                        result = value1 / value2;
                        break;
                    default:
                        result = 0;
                        break;
                }

                ViewBag.input1 = value1;
                ViewBag.input2 = value2;
                ViewBag.operation = operation;
                ViewBag.result = result;

            }

            return View("Result");
        }

        [HttpPost]
        public IActionResult Count3(int input1, int input2, string operation)
        {
            double result;

            switch (operation)
            {
                case "+":
                    result = input1 + input2;
                    break;
                case "-":
                    result = input1 - input2;
                    break;
                case "*":
                    result = input1 * input2;
                    break;
                case "/":
                    if (input2 == 0)
                        return View("ZeroErrorCalc");
                    result = input1 / input2;
                    break;
                default:
                    result = 0;
                    break;
            }

            ViewBag.input1 = input1;
            ViewBag.input2 = input2;
            ViewBag.operation = operation;
            ViewBag.result = result;

            return View("Result");
        }


        [HttpPost]
        public IActionResult Count4(Calc calc)
        {

            ViewBag.input1 = calc.first_value;
            ViewBag.input2 = calc.second_value;
            ViewBag.operation = calc.operation;
            ViewBag.result = calc.toCalc();
            if (ViewBag.result == -1)
                return View("ZeroErrorCalc");
            return View("Result");
        }
    }
}

Lab2/Views/Calc/ManualParsingInSeparateActions.cshtml
@{
    ViewData["Title"] = "ManualParsingInSeparateActions";
}
@using Lab2.App_code
<h2>ManualParsingInSeparateActions</h2>
<form method="post" action="~/Calc/Count2">
    @Html.CreateForm()
</form>

Lab2/Views/Calc/ManualParsingInSingleAction.cshtml
@{
    ViewData["Title"] = "ManualParsingInSingleActions";
}
@using Lab2.App_code
<h2>ManualParsingInSingleActions</h2>
<form method="post" action="~/Calc/Count1">
    @Html.CreateForm()
</form>

Lab2/Views/Calc/ModelBindingParametrs.cshtml
@{
    ViewData["Title"] = "ManualParsingInSeparateActions";
}
@using Lab2.App_code
<h2>ManualParsingInSeparateActions</h2>
<form method="post" action="~/Calc/Count3">
    @Html.CreateForm()
</form>

Lab2/Views/Calc/ModelBindingSeparateModel.cshtml
@{
    ViewData["Title"] = "ModelBindingSeparateModel";
}

@addTagHelper *, Lab2
<h2>ModelBindingSeparateModel</h2>
<form method="post" action="~/Calc/Count4">
    <input name="first_value" />
    <select name="operation">
        <Operation Add />
        <Operation Sub />
        <Operation Mult />
        <Operation Div />
    </select>
    <input name="second_value" />
    <input type="submit" />
</form>

Lab2/Views/Calc/Result.cshtml
@{
    ViewData["Title"] = "Result";
}

<h2>Result</h2>
<div>@ViewBag.input1 @ViewBag.operation @ViewBag.input2 = @ViewBag.result</div>

Lab2/Views/Calc/ZeroErrorCalc.cshtml
@{
    ViewData["Title"] = "ZeroErrorCalc";
}

<h2>Упс! Деление на ноль</h2>

Lab2/Views/Calc/index.cshtml
@{
    ViewData["Title"] = "Lab2 Home Page";
}
<h2>Form Parameters Parsing Demo</h2>
<ul>
    <li>
        <a href="/Calc/ManualParsingInSingleAction">Manual parsing in single action</a>
    </li>
    <li>
        <a href="/Calc/ManualParsingInSeparateActions">Manual parsing in separate actions</a>
    </li>
    <li>
        <a href="/Calc/ModelBindingParametrs">Model binding (parametrs)</a>
    </li>
    <li>
        <a href="/Calc/ModelBindingSeparateModel">Model binding (separate model)</a>
    </li>
</ul>

Lab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Calc" asp-action="Index" class="navbar-brand">Lab2</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Calc" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Lab2</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>